// Code generated by MockGen. DO NOT EDIT.
// Source: service/audioservice/repository.go

// Package mockaudioservice is a generated GoMock package.
package mockaudioservice

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetFilepath mocks base method.
func (m *MockRepository) GetFilepath(userId, phraseId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilepath", userId, phraseId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilepath indicates an expected call of GetFilepath.
func (mr *MockRepositoryMockRecorder) GetFilepath(userId, phraseId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilepath", reflect.TypeOf((*MockRepository)(nil).GetFilepath), userId, phraseId)
}

// Save mocks base method.
func (m *MockRepository) Save(userId, phraseId, filepath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", userId, phraseId, filepath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(userId, phraseId, filepath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), userId, phraseId, filepath)
}
